site_name: Imba guide
site_author: Hajime Yamasaki Vukelic
copyright: (C)2018 by Hajime Yamasaki Vukelic. Some rights reserved.
nav:
  - Level 0 - Intro:
    - index.md
    - lvl0/about.md
    - lvl0/sample.md
    - lvl0/structure.md
    - lvl0/tips.md
    - lvl0/javascript.md
    - lvl0/editors.md
  - Level 1 - Language basics:
    - lvl1/index.md
    - lvl1/comments.md
    - lvl1/statements.md
    - lvl1/operators.md
    - lvl1/primitives.md
    - lvl1/vars.md
    - lvl1/objects.md
    - lvl1/arrays.md
    - lvl1/regexps.md
    - lvl1/controls.md
    - lvl1/methods.md
    - lvl1/do.md
  - Level 2 - Advanced concepts:
    - lvl2/index.md
    - lvl2/modules.md
    - lvl2/classes.md
    - lvl2/tags.md
    - lvl2/async.md
    - lvl2/global.md
    - lvl2/listcomps.md
  - Bonus:
    - bonus/setup.md
    - bonus/testing.md
    - bonus/migration.md
    - bonus/escapes.md
    - bonus/memoized.md
    - bonus/typedet.md

markdown_extensions:
  - codehilite:
      guess_lang: false
      linenums: true
  - admonition
  - tables
  - toc:
      permalink: true

theme: readthedocs
